[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
